/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ApartadoGrafico;

import javax.swing.ImageIcon;

/**
 *
 * @author Edu18
 */
public class Informacion extends javax.swing.JFrame {

    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalirInformacion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GotThatTrivia");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(552, 635));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirInformacion.setBackground(new java.awt.Color(0, 0, 0));
        btnSalirInformacion.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Botones/BotonVolverInfoArr.png"))); // NOI18N
        btnSalirInformacion.setBorder(null);
        btnSalirInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGfondos/PanelInformacion.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 310, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGfondos/FondoInformacion .png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirInformacionActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirInformacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirInformacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
